### PR TITLE
Support additional messages & Dual licensing with MIT

### PR DESCRIPTION
**Pull request by elpiel**
- BOD (untested)
- GBS (untested)

### CODE REVIEW

**Comment by Dushistov** [comment]
I suppose that license change PR should not include any code changes.
Because of it need at least approve from all authors that contribute code to this crate,
or at least who contribute significant amount of code.

**Comment by elpiel** [comment]
On that note, @flxo do you mind moving your repository to the @aerorust org as it keeps defaulting to the original repo when opening PRs?

Do you agree to change the license to dual with MIT? I have added the copyright to both files.

@Dushistov do you agree to the change?

Ps: if everybody agrees I don't see why we should separated in a different PR. It is just more convenient to have it in the PR to get the confirmation right now.

**Comment by elpiel** [comment]
I opened #52 for the dual license change.

**Comment by flxo** [comment]
> On that note, @flxo do you mind moving your repository to the @AeroRust org as it keeps defaulting to the original repo when opening PRs?
> 
> Do you agree to change the license to dual with MIT? I have added the copyright to both files.

@elpiel I'm perfectly fine with that. Thanks.

**Pull request closed without merging**
