### PR TITLE
Use criterion for benchmarks and update bod parsing

### PR DESCRIPTION
**Pull request by clemarescx**
This PR introduces [`criterion`](https://github.com/bheisler/criterion.rs) as a dev-dependency to run benchmarks, instead of the nightly `bencher`.
The `gsv_parser` benchmark module now uses Criterion, and a new `nom_parsing` module has been added to compare parsing strategies for comma-separated values.
If we have `let sentence = "a,b";` the strategies are:
- the "discard comma" strategy already used in the crate:
  ```rust
  let (i, a) = char('a')(text)?;
  let (i, _) = char(',')(i)?; // the parsed comma is discarded with _
  let (i, b) = char('b')(i)?;
   ```
- the `preceded` combinator:
  ```rust
  let (i, a) = char('a')(text)?;
  let (i, b) = preceded(char(','), char('b'))(i)?;
  ```
Run `cargo bench` to run the benchmarks.

I initially thought that there would be significant performance improvement by using `preceded`, but it turns out that it's slightly slower. Therefore I also included an update of the parsing strategy for the BOD sentence (that I had previously worked on), to be like the other parsers in the crate and use the discard-comma strategy.

### CODE REVIEW

**Comment by clemarescx** [comment]
That's weird, the CI fails due to `os_str_bytes 6.3.1` which is a transitive dependency of `criterion`, because it requires Rust v1.57... but the `Cargo.toml` file of the `nmea` crate specifies `rust-version = "1.56"`.
According to the [Cargo book regarding this field](https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=rust-version#the-rust-version-field). this "[...] affect all targets/crates in the package, including test suites, benchmarks, binaries, examples, etc."....

**Comment by elpiel** [comment]
I think that it should give you the error when compiling as it did.
And yes, downgrading should working, as we see in the CI build.

`criterion` only specifies the edition but no MSRV, maybe that's the reason `os_str_bytes` is giving the error rather than `criterion`.

I think we should also add the benchmarking to CI, if it's possible to add a report - even better!

Thanks for working on the benchmarking :tada:

**Review by elpiel — APPROVED** [review]

**Comment by clemarescx** [comment]
Well, the `criterion` docs [discourage benchmarks in CI pipeline](https://bheisler.github.io/criterion.rs/book/faq.html#how-should-i-run-criterionrs-benchmarks-in-a-ci-pipeline) with `criterion`, as the results are unreliable on VMs.

But regardless I'd vote for a separate feature request/PR for adding benchmark runs in the CI pipeline, and decide there what the reports will be like and how they will be run.

For now, it's just nice not to need `+nightly` for running `cargo bench` locally I think :yum:

**Comment by elpiel** [comment]
Ok, I agree then not to have it in CI and it is nice to be independent from nightly 😁

Would be nice to mention how to run benchmarks it in the readme, but they would be done once we have a good benchmark to run

**Pull request merged**
